# Generated by Django 4.2.3 on 2023-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('url', models.URLField(unique=True, verbose_name='ссылка')),
                ('bitlink', models.URLField(blank=True, null=True, verbose_name='битлинк')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('active', models.BooleanField(default=True, verbose_name='ссылка активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
            ],
            options={
                'verbose_name': 'реферальная ссылка',
                'verbose_name_plural': 'реферальные ссылки',
            },
        ),
    ]
