# Generated by Django 4.2.2 on 2023-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bitlink',
            field=models.URLField(blank=True, null=True, verbose_name='битлинк'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(unique=True, verbose_name='ссылка'),
        ),
    ]
