# Generated by Django 4.2.3 on 2023-07-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('NC', 'Не выбрано'), ('WO', 'Без ягод'), ('RA', 'Малина'), ('BL', 'Голубика'), ('BB', 'Ежевика'), ('ST', 'Клубника')], default='NC', max_length=256, verbose_name='Название ягоды')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена ягоды')),
            ],
            options={
                'verbose_name': 'Ягода',
                'verbose_name_plural': 'Ягоды',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=256, verbose_name='Номер телефона заказчика')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя заказчика')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия заказчика')),
                ('address', models.TextField(verbose_name='Адрес заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('NC', 'Не выбрано'), ('WO', 'Без декора'), ('PI', ' Фисташки'), ('ME', 'Безе'), ('PE', 'Пекан'), ('MM', 'Маршмеллоу'), ('MC', 'Марципан')], default='NC', max_length=256, verbose_name='Наименование декора')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена декора')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декор',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('No', 'Не выбрано'), ('ON', 'Один'), ('TW', 'Два'), ('TH', 'Три')], default='No', max_length=256, verbose_name='Уровни торта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена уровня')),
            ],
            options={
                'verbose_name': 'Количество уровней',
                'verbose_name_plural': 'Количество уровней',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('NC', 'Не выбрано'), ('CI', 'Круг'), ('SQ', 'Квадрат'), ('RE', 'Прямоугольник')], default='NC', max_length=256, verbose_name='Наименование формы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена формы')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('No', 'Не выбрано'), ('WO', 'Без топпинга'), ('WS', 'Белый соус'), ('CA', 'Карамельный'), ('MA', 'Кленовый'), ('BB', 'Черничный'), ('WC', 'Молочный шоколад'), ('ST', 'Клубничный')], default='No', max_length=256, verbose_name='Наимнование топпинга')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена топпинга')),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинг',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('ne', 'Создан'), ('PA', 'Оплачен'), ('CO', 'Готовится'), ('IND', 'В доставке'), ('DE', 'Доставлен')], default='', max_length=256, verbose_name='Статус заказа')),
                ('title', models.TextField(blank=True, verbose_name='Надпись')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.DateTimeField(verbose_name='Время доставки')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость заказа')),
                ('berries', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeshopapp.berry', verbose_name='Ягоды')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='bakeshopapp.customer', verbose_name='Заказчик')),
                ('decor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeshopapp.decor', verbose_name='Декор')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeshopapp.shape', verbose_name='Форма')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeshopapp.level', verbose_name='Количество уровней')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakeshopapp.topping', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
