# Generated by Django 4.2.3 on 2023-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(verbose_name='Время доставки'),
        ),
    ]
