# Generated by Django 4.2.3 on 2023-07-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakeshopapp', '0002_alter_order_delivery_time'),
        ('bakeshopapp', '0004_alter_customer_user'),
    ]

    operations = [
    ]
