# Generated by Django 4.2.3 on 2023-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeshopapp', '0006_rename_cake_bake_rename_cake_order_bake_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bake',
            old_name='form',
            new_name='shape',
        ),
        migrations.AlterField(
            model_name='shape',
            name='name',
            field=models.CharField(blank=True, default='CIRCLE', max_length=256, verbose_name='Наименование формы'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(blank=True, default='WITHOUT', max_length=256, verbose_name='Наименование начинки'),
        ),
    ]
