# Generated by Django 4.2.3 on 2023-07-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeshopapp', '0007_rename_form_bake_shape_alter_shape_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bake',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bakes/', verbose_name='Изображение торта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='bakeshopapp.customer', verbose_name='Заказчик'),
        ),
    ]
