# Generated by Django 4.2.3 on 2023-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeshopapp', '0010_bakecategory_bake_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка категории'),
        ),
    ]
